version: '2'
services:
    javacloud-app:
        image: javacloud
        external_links:
            - javacloud-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=javacloud
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    javacloud-mongodb:
        extends:
            file: mongodb.yml
            service: javacloud-mongodb
