version: '2'
services:
    javacloud-mongodb:
        container_name: javacloud-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        command: mongos --configdb javacloud-mongodb-config
    javacloud-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    javacloud-mongodb-config:
        image: mongo:mongo:3.3.12
        container_name: javacloud-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
