version: '2'
services:
    javacloud-mongodb:
        container_name: javacloud-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/javacloud/mongodb/:/data/db/
